### ISSUE TITLE
Testing Signup forms in Venue.voletix.io

### ISSUE THREAD

**Issue by Mojganahk** [Volentix/venue-client#251]
Rhys ,
Once the live version of venue.volentix.io is up and running, please inform me, Matthew and Marwan to test the signup forms.
Thanks

**Comment by Mojganahk** [comment]
Mojgan Ahmadi, Creative Director Edited 1:28pm

Sign-up form Name:  VenuePostBeta (Turkish)
Contacts list name:  VenuePostBeta (Turkish)
https://app.constantcontact.com/pages/contacts/list-growth#edit/formId/ece61f5e-aaf5-4b47-9a75-5c5a0c505304

Turkish inline Code:

<div class="ctct-inline-form" data-form-id="ece61f5e-aaf5-4b47-9a75-5c5a0c505304"></div>

===============================
English Version
Sign-up form Name:  VenuePostBeta
Contacts list name:  VenuePostBeta
https://app.constantcontact.com/pages/contacts/list-growth#edit/formId/121aa524-2753-4c1f-85d7-e582b70bd983

English inline Code:

<div class="ctct-inline-form" data-form-id="121aa524-2753-4c1f-85d7-e582b70bd983"></div>

**Comment by shawnlauzon** [comment]
@Mojganahk Is this done?

**Comment by Mojganahk** [comment]
@shawnlauzon English version was tested. 
Turkish one not yet. 
let me know if I can test the turkish one. I don't know the website address.

**Comment by shawnlauzon** [comment]
@realrhys Please provide Turkish URL so that @Mojganahk can verify the signup form.

**Comment by shawnlauzon** [comment]
I believe this is done; @Mojganahk please reopen if not the case.
