### ISSUE TITLE
Text for sharing a referral link

### ISSUE THREAD

**Issue by Lyncis** [Volentix/venue-client#253]
Text for sharing user's referral link on Twitter, Facebook and other platforms is needed.
![image](https://user-images.githubusercontent.com/8875863/43793007-4c035106-9a48-11e8-8952-19b972c1c26a.png)

Child of Volentix/venue#8

**Comment by Mojganahk** [comment]
I will let you know ASAP.

**Comment by shawnlauzon** [comment]
@mojganahk please keep this open until the text is added, thank you.

**Comment by Mojganahk** [comment]
sure @shawnlauzon , my bad, I hit the button accidentally.

**Comment by Mojganahk** [comment]
TEXT:

 Use this referral link to sign up to earn VTX bounties on venue.volentix.io. The Volentix Project is a collaborative effort, building software to enhance the utility and security of cryptocurrency. Have you heard of VDEX ? It is a decentralized exchange built on EOS. Maybe it’s time to get involved ?  


IMAGE:
![ecosystem-moreInfo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46ed9795309b90bd8ae4f24eab4ff5bd274028316546b3397f8fe62bab0021435a0e18a9150c0b43a9ad8f7ea2b73c708b085abbd965597cd42103eee9dc4be05ce36ade0d97bcae8b45cae93826e4838d4c381a041f8dff4f78.jpg)

Please note that >>>>> venue.volentix.io in the TEXT, is linked to Venue platform.

**Comment by Mojganahk** [comment]
@shawnlauzon

**Comment by Lyncis** [comment]
I just tried this on twitter and it exceeded the word limit, and I haven't even added the referral link. 

![image](https://user-images.githubusercontent.com/8875863/43904580-023b2564-9bbd-11e8-9391-5797ff83e0eb.png)

**Comment by Mojganahk** [comment]
How about this? >>>>>

Use this referral link to sign up to earn VTX bounties on venue.volentix.io. Have you heard of VDEX ? It is a decentralized exchange built on EOS. Maybe it’s time to get involved ?

<<<<

**Comment by Mojganahk** [comment]
this one is better if you have enough limit.
>>>>>
Use the referral link to sign up to earn VTX bounties on venue.volentix.io. Volentix is building software to enhance the security of cryptocurrency. Have you heard of VDEX ? It is a decentralized exchange built on EOS. it’s time to get involved.

<<<<<

**Comment by Mojganahk** [comment]
yes please, same text for all platforms,  just to remind that please attach the IMAGE with the TEXT.
BTW could you pls send me a screenshot of the invite friend page in Basecamp?

**Comment by Lyncis** [comment]
yeah, sure!

Can I get a link on Basecamp? I don't think I was invited there

**Comment by shawnlauzon** [comment]
@Mojganahk @Lyncis This is an open source project; other users do not have access to Basecamp. Just attach the screenshot here.

**Comment by Lyncis** [comment]
@Mojganahk 
![image](https://user-images.githubusercontent.com/8875863/43915870-ffaf50a0-9bd9-11e8-80a6-2eda5ee3cff5.png)

**Comment by Mojganahk** [comment]
Thanks @Lyncis  
FYI, you have basecamp account. https://3.basecamp.com/3982250/circles/8677022

**Comment by Lyncis** [comment]
@Mojganahk I can add the image to the sharing only if it is on Pinterest. Library for social sharing doesn't allow to attach images in any other way.

![image](https://user-images.githubusercontent.com/8875863/44097848-bb2a237a-9fac-11e8-8661-9ce2f6fde4fa.png)

**Comment by Mojganahk** [comment]
@Lyncis I see. Can the image be included in **content** of that URL?

**Comment by Lyncis** [comment]
@Mojganahk I can try it, but I am not sure

**Comment by Lyncis** [comment]
@Mojganahk 
Did you mean the thumbnail (preview) of the website?
Like this?
![image](https://user-images.githubusercontent.com/8875863/44100757-bd04f25e-9fb3-11e8-88ed-c062c373cbb1.png)

^ yes, it automatically added by the twitter/facebook/linkedin/etc

I put github there just for example to demonstrate the preview.

**Comment by Mojganahk** [comment]
@Lyncis The thumbnail is good, and when the link's clicked, the image can be visible in the content preferably.
