### ISSUE TITLE
Wrong user highlighted in leaderboard

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-client#257]
**Describe the bug**
The user who is logged in is not being highlighted; a different user is

**To Reproduce**
1. Sign in
2. Click on Leaderboard
3. See that a different user than me is highlighted

**Expected behavior**
My user should be highlighted

**Screenshots**
Hawkeye is highlighted
![image](https://user-images.githubusercontent.com/611529/43911355-41cbaa0e-9bcd-11e8-9173-8d77ef3ddb22.png)

But I am antman
![image](https://user-images.githubusercontent.com/611529/43911368-4f1a33ce-9bcd-11e8-96c0-8bf02b82f6d1.png)

**Additional context**
N/A

**Comment by shawnlauzon** [comment]
It's weird; the data in Nuxt seems to be bad:

The `user` data is correct:
![image](https://user-images.githubusercontent.com/611529/43912017-059b7986-9bcf-11e8-881d-51447442a275.png)

But the `userStats` is wrong (antman is rank 8)
![image](https://user-images.githubusercontent.com/611529/43911992-f4bdc83a-9bce-11e8-9b5f-a26bc43c3b34.png)

**Comment by Lyncis** [comment]
seems like it highlights all users with the same number of tokens wrong (highlights the last one of them in the list)

**Comment by shawnlauzon** [comment]
Apparently this only happens in a local installation; will have to address it later.

**Comment by shawnlauzon** [comment]
This definitely is still a problem, and it seems to have to do with logging in and logging out. Will investigate now.

**Comment by alexdashkov** [comment]
What is the priority? I'd like to start it when I'll finish with the stats endpoint, does it make sense?

**Comment by shawnlauzon** [comment]
PM'd.

**Comment by alexdashkov** [comment]
This issue should be fixed with the stats PR

**Comment by shawnlauzon** [comment]
Looks good to me!
