### ISSUE TITLE
Correct number of friends not displayed

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-client#258]
**Describe the bug**
"0 friends | 1 friend | 0 friends" is displayed, and should say just 0

**To Reproduce**
1. Sign in
2. Click on Invite a Friend

**Expected behavior**
Show the number of people who have been referred by me.

**Screenshots**
![image](https://user-images.githubusercontent.com/611529/43911507-a9b3b5a8-9bcd-11e8-9aed-df9d150735fa.png)

**Additional context**
N/A

Child of Volentix/venue#8

**Comment by Lyncis** [comment]
I fixed this, but haven't committed yet since I am also doing some minor fixes

**Comment by Lyncis** [comment]
Now the correct number of friends is displayed:

![image](https://user-images.githubusercontent.com/8875863/44109046-10ea1014-9fca-11e8-8fc1-c99579a19f2f.png)
