### ISSUE TITLE
Final UI changes for referral campaign

### ISSUE THREAD

**Issue by Mojganahk** [Volentix/venue-client#259]

**Comment by Lyncis** [comment]
ok, cool! Got it

**Comment by Lyncis** [comment]
@Mojganahk @shawnlauzon 
how critical is to center the table content? It seems that Bulma doesn't have any options to center the labels. I found a lot of issues on GitHub with people trying to do the same thing. 

So far I couldn't find a valid solution, some of them simply doesn't work, some of them identified by eslintrc/prettier as an error.

The only way I see is to create the whole table manually, without using b-column 

![image](https://user-images.githubusercontent.com/8875863/44042318-f12db1c2-9eed-11e8-9221-28b3f140d375.png)

**Comment by Mojganahk** [comment]
@Lyncis It would be nicer in center. If it doesn't allow, let's keep it the way it was but with more space on the left. thanks.

**Comment by shawnlauzon** [comment]
@Lyncis I imagine you've already tried this, but how about simply putting it inside a [container](https://bulma.io/documentation/layout/container/)?

**Comment by Lyncis** [comment]
@shawnlauzon I've tried, but it doesn't center the labels.
I might be wrong here, but it is quite desirable I can create the table directly using <th> and <td>. In this case everything will be centered

**Comment by shawnlauzon** [comment]
@Lyncis Yes, as a last resort (and it appears we are at that point), using a table is fine.
