### ISSUE TITLE
Center table content

### ISSUE THREAD

**Issue by Lyncis** [Volentix/venue-client#262]
The text in the table on Invite a Friend page has to be centered.
Seems like it is a common issue with Bulma, I found different issues on GitHub. All the suggested solutions don't work.
I tried to create a table manually, but I get the render error and table is generated several times.

**Comment by Lyncis** [comment]
solved
![image](https://user-images.githubusercontent.com/8875863/44108038-2e317728-9fc7-11e8-9ff5-5459ffad0b3b.png)

**Comment by shawnlauzon** [comment]
Those arrows being centered looks weird; they are normally on the right side of the table, and they should be like that here too.

Please open another issue and resolve that separately so it doesn't hold up the release.

**Comment by Lyncis** [comment]
I followed the mockup and it has buttons and arrows centered.
Mockup from #259 
![image](https://user-images.githubusercontent.com/8875863/44108396-462f1320-9fc8-11e8-88e0-a64531f66544.png)

I can remove centering for buttons at all and move that to the right or create another issue as you said.
