### ISSUE TITLE
Image or thumbnail for the posts

### ISSUE THREAD

**Issue by Mojganahk** [Volentix/venue-client#265]
**Describe the bug**
the post as we discussed has no image. 

**Expected behavior**
showing a thumbnail or image if it's possible. this is so simple.

**Screenshots**
I have put it below the description.

thanks @Lyncis

**Comment by Mojganahk** [comment]
![photo_2018-08-14_15-09-07.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46f89c95378dbcfbdfb8e70ef405bdc57d7976266454fa6620d2a164fd52690e050a1de853524d41adaf8c7ff2e23b25de5a5ee9d06d5f75926c47a4b08417ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b061c8bf85e3da1904fc85ce406.jpg)

@Lyncis

**Comment by Lyncis** [comment]
I'll try to check what I can do about this, but I am not sure that I am able to change this since its all done automatically.

**Comment by Lyncis** [comment]
The library that I use is using sharing links. I'll check if it is possible to attach the thumbnail. If it is not, I'll check API and might switch to API calls then.

**Comment by Lyncis** [comment]
1. It is possible that we can use our own thumbnail with the sharing link, but I can't test it. If we include this in the meta, it might load this image when generating the sharing post:

`{
        property: "og:image",
        content:
          "http://image_url"
}`

But I can't test it locally (Facebook is blocking it).

2. I tried Facebook Javascrip SDK, but it doesn't work on our project. Object FB is always undefined and I couldn't find a way to fix this now. Official documentation says this:

`The Facebook SDK for JavaScript doesn't have any standalone files that need to be downloaded or installed, instead you simply need to include a short piece of regular JavaScript in your HTML`

Official documentation example also doesn't work (FB is not defined). 

https://developers.facebook.com/docs/javascript/quickstart

**Comment by shawnlauzon** [comment]
1. Since it won't break anything, you can push it into dev and see if it works
2. You can add scripts into the Nuxt config file; [see this example](https://github.com/nuxt/nuxt.js/blob/dev/examples/meta-info/pages/index.vue#L18)

**Comment by Lyncis** [comment]
1. I made PR, we'll see if it works after it gets merged.
2. Tried different solutions, keep getting the same error. I am not sure we can make it work.

3. Twitter doesn't allow to pass thumbnail or image, it accepts only text, URL, title, and hashtags.

**Comment by shawnlauzon** [comment]
@Mojganahk If we can't push images through social media, should we keep the links or remove them?

**Comment by Mojganahk** [comment]
You mean there would be only one option(sending email )?
![mm.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46e599d86fc093bb80e3ba40b01faad67c4721262d00a77c7581b52deb132b515e0b1ffa4950594ceee59b69f7e8682fd70541b8937f5566c73a1badbd811bba00b223834787b0b99801.jpg)

**Comment by shawnlauzon** [comment]
If we removed the social media icons, correct. But that's my question to you from the perspective of marketing / design: Is it better to have social media icons which post information without photos or to remove the icons completely?

**Comment by Mojganahk** [comment]
let's keep the social media icons with post without photo, this will be better than nothing.
