### ISSUE TITLE
Translate referral strings to Turkish

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-client#273]
The translated file did not include the strings for referral bonus. I've added the new strings into the Turkish file (they are in English); the file [is here](https://github.com/Volentix/venue-client/blob/master/venue/lang/tr-TR.js)

**Comment by Mojganahk** [comment]
Sent to translator.

**Comment by Mojganahk** [comment]
https://waffle.io/Volentix/venue/cards/5b75ac761fdcd5001334c118
