### ISSUE TITLE
User can view Turkish version of referral email on website

### ISSUE THREAD

**Issue by shawnlauzon** [Volentix/venue-client#285]
Place the [see Volentix/venue-server#181](Turkish email) on the website. Accept two query parameters on the URL and use them for replacement text in the email:

`?referrer_name=<name>&code=<code>`

Child of Volentix/venue-server#181

**Comment by Lyncis** [comment]
1. I need to get email text from @Mojganahk 
2. Should it look like this? referrer_name and code are accepted from the url and then used to form the referral link. `Follow this link to sign up` leads to the signup page and passes referrer_name and code.
![screen shot 2018-08-20 at 1 40 49 pm](https://user-images.githubusercontent.com/8875863/44356914-b2f47580-a47e-11e8-98f4-9d5888b4da18.png)

**Comment by shawnlauzon** [comment]
No, the `referrer_name` and `code` are used to fill in the body of the email. Inside the body of the email is the link to sign up.

And also, I would like the URL to not go exactly to what looks like Venue, but instead is a full screen with just the contents of the email, and then the link in the body brings the user to Venue.

Make sense?

**Comment by Lyncis** [comment]
I got the html body for the email from @Mojganahk 
I just need to know where to add the name and referral code.

**Comment by Lyncis** [comment]
@Mojganahk Don't need anything right now, you already showed me everything :)
I was asking about where exactly I need to put the friend's name in the email body. You already showed it.

**Comment by Mojganahk** [comment]
@Lyncis  Perfect :)

**Comment by Lyncis** [comment]
I couldn't use the body of the html.
I am waiting for another one now.
Retrieving of the username from the URL and using it in the email body is already working. 
Sign Up link with the referral code is also working (if we need it)

**Comment by Mojganahk** [comment]
@Lyncis
This is the clean code as you had requested. please let me know if this can be approved.
http://msalman1111.xyz/templates/template7/

Thanks,

**Comment by Lyncis** [comment]
@Mojganahk 
Yes, I can use this :) thank you

**Comment by shawnlauzon** [comment]
Since you have a new version of the HTML, there needs to be an English version with the same structure, and that needs to be uploaded to the server.

@Mojganahk and @Lyncis, please work with @alexdashkov to ensure that the email on the client and the server is the same, except for the language. This way translation will be smooth going forward. This should also solve the problem Volentix/venue#143

**Comment by Mojganahk** [comment]
[Delivery.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46cc91962a9486bb96abf301b44fff9e2c4533317346f62a76d0e72cbb157e05590a4aad41585e10adaf8123a0be2e6c981e5ab38532022d8c6853beb2901eb70bbb25884b8cb3ba834ac4ed3e2cf5c6.zip) @Lyncis  the Zip is the final file.

**Comment by Mojganahk** [comment]
@Lyncis  this is the ENGLISH version of the clean HTML code,  
http://msalman1111.xyz/html/html1/
Please let me know if that's ok.

**Comment by Lyncis** [comment]
@Mojganahk Yes, it is ok.

**Comment by Mojganahk** [comment]
@Lyncis ,
Cool, so this is the zip file.
[Delivery-En.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46cc91962a9486bb96a49a4de611b2843b492d762a10e17132d0e22eea467f05580a1aaa145c5e44fcf8dd7af0be3476824e17ff933c0120996048e6edc00db513b820814e80b5b98a48c0ec3c24e0898e5d73.zip)

**Comment by alexdashkov** [comment]
I've compared the files and there is some difference between the versions. 
Some comments: 

- is it possible to have only one file instead of a folder at least for the English version? 
- do you really need jquery and bootstarp.js? 

@shawnlauzon how do you want to host a turkish version?

**Comment by shawnlauzon** [comment]
@alexdashkov Turkish version is hosted on Venue server.

**Comment by alexdashkov** [comment]
@shawnlauzon yes, I got this from the discussion, I'm asking about where **exactly**. Should I return it from the backend or you have some CDN where I can store it?

**Comment by shawnlauzon** [comment]
No, the English email has a link to the Turkish version which is permanently hosted on the Venue web application (I just realized I said Venue server and I misspoke about that, very sorry -- I meant hosted on the Venue webapp)

**Comment by Mojganahk** [comment]
The content  in turkish version was corrected. @alexdashkov  
please use this file.
Thank you so much!

[Delivery-TR-edited.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b1aea6058b8350011a807fc/125516c66e82c728ace21e0d46cc91962a9486bb96a48b71e958f49d3d4323316546b3397f8fe62bab0021435a0e18a9150c0b43a9ad8f7ea2b73c708b085abbd965597cd42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e28b8b4a371b041a8afa4f78.zip)

**Comment by alexdashkov** [comment]
I changed the English version of the email and made a PR with it. However, I  don't touch the Turkish version. As we've discussed with @shawnlauzon and @Lyncis front should generate it.
