### ISSUE TITLE
Fix the error display

### ISSUE THREAD

**Issue by Lyncis** [Volentix/venue-client#298]
Error message should be displayed under the input field

![screen shot 2018-08-29 at 5 15 04 pm](https://user-images.githubusercontent.com/8875863/44867435-c3aea380-ac55-11e8-9883-97e44c0a134e.png)

**Comment by Lyncis** [comment]
@shawnlauzon 
I checked Bulma and Buefy documentation and looked through some issued on GitHub. It looks like "required" fields with both labels and addons don't get laid out properly. 

It was displayed correcly before because we used an array of strings to display the message. When I replaced the array with a single string, I started to get the same bug.

I found the way to display the error message below the field:

![screen shot 2018-08-31 at 10 00 38 am](https://user-images.githubusercontent.com/8875863/44916891-cf0cd800-ad04-11e8-8a08-11c8fb33c06d.png)

However, this solution doesn't change the way of the error that is displayed when user doesn't fill the required field (since this error message is generated in a different way):

![screen shot 2018-08-31 at 9 57 53 am](https://user-images.githubusercontent.com/8875863/44916680-5efe5200-ad04-11e8-97a6-74b0d386bb06.png)

I checked if the size of the field can somehow affect the message placement and I couldnt' find anything about it. I tried to play with it, but I always got the same result.

**Comment by Lyncis** [comment]
The problem is in the length of the strings. If the string is too short, it displays it on the right side:
![screen shot 2018-09-10 at 12 56 47 pm](https://user-images.githubusercontent.com/8875863/45312024-00ea1f80-b4f9-11e8-9988-5de9deed6196.png)

If I replace any string with a bigger one, it moves the message below the input.
![screen shot 2018-09-10 at 12 59 07 pm](https://user-images.githubusercontent.com/8875863/45312167-57575e00-b4f9-11e8-8e11-d802dc4bdaf0.png)

I am not able to change the way it displays the message. I think we should use a longer sentences for the error or remove the message as an addon and implement it via <p> tag. It will look like this:

![image](https://user-images.githubusercontent.com/8875863/45312325-c59c2080-b4f9-11e8-94d1-38b730e6c90a.png)

**Comment by shawnlauzon** [comment]
Looks to me that there's just too much space to the right of the Verify button. Can you make that field fill up all the remaining horizontal space?
