### ISSUE TITLE
Usernames and emails of users signed up to Venue

### ISSUE THREAD

**Issue by Mojganahk** [Volentix/venue-client#299]
Shawn, there are two question:

- [x] If any user can signup on Venue.volentix.io ?
- [ ] And also is it possible to collect new signups in constant contact email list?

if so, that's ok, if not Marketing needs that.
Thanks,

https://venue.volentix.io/signup

**Comment by Mojganahk** [comment]
Matthew, I will add you @volentixnonton11  here to be in the loop.

**Comment by shawnlauzon** [comment]
Yes anyone can signup on venue.volentix.io (although this is so obviously a YES, I wonder if I am misinterpreting your question).

Second, emails right now are not sent to constant contact, but that can probably be done (I believe there is an API for it). It can be scheduled for next iteration if you would like.

**Comment by Mojganahk** [comment]
@shawnlauzon  what is important for now, is having a record of all emails.  
constant contact is not urgent for now, but can be prioritized.

**Comment by shawnlauzon** [comment]
Yes, we retain all emails.

**Comment by Mojganahk** [comment]
How we can have access to those emails?

**Comment by shawnlauzon** [comment]
Email with users and emails set to @Mojganahk
